[general]
    neurons = 1
    synapses = 0
    n_neurons = 8784
    n_input_neurons = 784
    n_output_neurons = 10
    n_synapses = 0
    n_input_synapses = 0
    n_output_synapses = 0
	output_file = "configuration_files/networks/network8784_hc.toml"
    output_is_separated = 1
	lambda = 2
    lambda_delays = 0.75
    integers = 0
    max_connections_pair_neurons = 8

[neurons]
    v_thres = 1
    v_thres_min = -50
    v_thres_max = -40

    v_rest = 1
    v_rest_min = -65
    v_rest_max = -60

    R = 1
    R_min = 1
    R_max = 1

    refract_time = 1
    refract_time_min = 1
    refract_time_max = 10

    behaviour = 1
    behaviour_min = 0
    behaviour_max = 1

[synapses]
    latency = 1
    latency_min = 1
    latency_max = 20

    training_zone = 1
    training_zone_min = 1
    training_zone_max = 1

    weight = 1
    weight_min = 0.5
    weight_max = 2.5