#include <stdlib.h>
#include <stdio.h>

#include "metrics.h"



// shuffle indexes
void shuffle_sample_indexes(int *indexes, int n) {
    
    for (int i = n - 1; i > 0; i--) {
        int j = rand() % (i + 1);
        int tmp = indexes[i];
        indexes[i] = indexes[j];
        indexes[j] = tmp;
    }
}


// creates batches from the dataset
int* create_batches(int *n_batches, int *extra_samples, input_data_t *dataset, int n_samples, int batch_size){

    int i;
    int *batches;
    
    // initialize extra samples
    (*extra_samples) = 0;

    // set number of batches
    if(n_samples < batch_size)
        (*n_batches) = 1;

    // add empty elements to allow batches
    else if((n_samples % batch_size) > 0){
        
        (*n_batches) = (n_samples / batch_size) + 1;
    }
    else{
        (*n_batches) = (n_samples / batch_size);
    }

    // allocate memory for batches
    batches = (int*)malloc((*n_batches) * batch_size * sizeof(int));

    // initialize
    for(i=0; i<n_samples; i++){
        batches[i] = i;
    } 

    for(i; i<(*n_batches) * batch_size; i++){
        batches[i] = -1;
    }

    (*extra_samples) = ((*n_batches) * batch_size) - n_samples;

    printf("N batches = %d, batch_size = %d\n", (*n_batches), batch_size);
    printf("Total n = %d, n = %d, Extra samples = %d\n", (*n_batches) * batch_size, n_samples, (*extra_samples));

    return batches;
}


float accuracy_by_output_neurons(simulation_results_t *results, input_data_t *dataset, int *batches, int batch_size, int batch, int n_out){
    
    int i, j, acc, *pred, *output_spikes, max, index;

    // count the number of spikes produced by each output neuron
    /*for(i = 0; i<n_samples; i++){
        
        // count the number of spikes generated by the 
        for(j = 0; j<n_output; j++){
                output_spikes[i] += results->results_per_sample[i].n_spikes_per_neuron[n_neurons - j];
        }
    }*/


    // loop over samples
    for(i = 0; i<batch_size; i++){

        // compute probabilities
        max = 0; 
        index = 0;

        // loop over output neurons
        for(j = 0; j<n_out; j++){

            // get the neuron that most spikes generated
            if(results->results_per_sample[batches[batch_size * batch + i]].n_spikes_per_neuron[j] > max){
                
                // store the index
                index = j;
                // store the number of spikes
                max = results->results_per_sample[batches[batch_size * batch + i]].n_spikes_per_neuron[j];
            }
        }

        // compare
        if(index == dataset->labels[batches[batch_size * batch + i]])
            acc ++;
    }

    return acc;
}