#include <stdlib.h>

#include "metrics.h"



// shuffle indexes
void shuffle_sample_indexes(int *indexes, int n) {
    
    for (int i = n - 1; i > 0; i--) {
        int j = rand() % (i + 1);
        int tmp = indexes[i];
        indexes[i] = indexes[j];
        indexes[j] = tmp;
    }
}


// creates batches from the dataset
int* create_batches(int *n_batches, input_data_t *dataset, int n_samples, int batch_size){

    int i;
    int *batches;

    // add empty elements to allow batches
    if((float)n_samples / (float)batch_size > 0.0){
        
        (*n_batches) = (n_samples / batch_size) + 1;
    }
    // only 1 batch 
    else if((float)(n_samples) / (float)(batch_size) < 0.0){
        *n_batches = 1;
    }

    // allocate memory for batches
    batches = (int*)malloc((*n_batches) * batch_size * sizeof(int));

    // initialize
    for(i=0; i<n_samples; i++){
        batches[i] = i;
    } 
    for(i=i; i<(*n_batches) * batch_size; i++){
        batches[i] = -1;
    }

    return batches;
}


float accuracy_by_output_neurons(simulation_results_t *results, input_data_t *dataset, int *batches, int batch_size, int batch, int n_out){
    
    int i, j, acc, *pred, *output_spikes, max, index;

    // count the number of spikes produced by each output neuron
    /*for(i = 0; i<n_samples; i++){
        
        // count the number of spikes generated by the 
        for(j = 0; j<n_output; j++){
                output_spikes[i] += results->results_per_sample[i].n_spikes_per_neuron[n_neurons - j];
        }
    }*/


    // loop over samples
    for(i = 0; i<batch_size; i++){

        // compute probabilities
        max = 0; 
        index = 0;

        // loop over output neurons
        for(j = 0; j<n_out; j++){

            // get the neuron that most spikes generated
            if(results->results_per_sample[batches[batch_size * batch + i]].n_spikes_per_neuron[j] > max){
                
                // store the index
                index = j;
                // store the number of spikes
                max = results->results_per_sample[batches[batch_size * batch + i]].n_spikes_per_neuron[j];
            }
        }

        // compare
        if(index == dataset->labels[batches[batch_size * batch + i]])
            acc ++;
    }

    return acc;
}