#ifndef SNN_LIBRARY_H
#define SNN_LIBRARY_H

#include "stdio.h"

// TODO: Max spikes should be an input parameter?


#ifdef USE_DOUBLE
    typedef double real_t;
#else
    typedef float real_t;
#endif

// temporal thrN
#define thrN 16

/* Simulation configuration struct containing all the data for the simulation */

/// @brief Struct to load all the configuration data
typedef struct{

    // [general] information
    int simulation_type; // clock (0) / event-driven (1)
    int neuron_type; // neuron type (LIF...)
    int simulation_obj; // simulation obj. (ML or biological simulations) // DEPRECATED???
    size_t n_process; // number of CPU processes
    size_t n_inner_process;
    int cuda; // simulation done in cuda
    int multi_gpu; // multi gpu simulation allowed or not: not (0), auto (1), maximize (2, use all available gpus)
    int learn; // inference (0) / training (1)
    int encode; // input encoded (0) / encode input (1) // TODO
    size_t batch_size; // batch size

    // [simulation] data
    size_t time_steps; // time steps of the simulations
    size_t max_spikes; // length for arrays in the middle of the network
    size_t max_input_spikes; // length for input and output neurons arrays
    size_t epochs; // number of epochs to simulate

    // [dataset] data
    int train_provided;
    char *train_set; // path to the file that contains the train set
    char *train_labels; // path to the file that contains the labels of the train set
    size_t n_train; // number of samples in the training set

    int test_provided; // indicates if a test set exists (1) or not (0)
    char *test_set; // path to the file that contains the test set
    char *test_labels; // path to the file that contains the labels of the test set
    size_t n_test; // number of samples in the test set
    
    char *dataset_name; // name of the simulated dataset
    size_t n_classes; // number of classes in the dataset
    size_t input_size;

    int shuffle_samples; // whether samples should be shuffled or not

    // [output] data
    int store_generated_spikes, store_n_spikes, store_execution_times, store_network;
    char *generated_spikes_file; // file path to store the spike generated
    char *n_spikes_per_neuron_file; // file path to store the number of spikes generated by each sample
    char *execution_times_file; // file path to store the execution times
    char *store_network_file; // file path to store the final network
    FILE *f_gs, *f_ns, *f_et, *f_sn;

    // [network] section
    char *network_file; // file path to load the network from 
    char *network_neurons_file; // file path to load network neurons from 
    char *network_synapses_file; // file path to load network synapses from

    // control variables to indicate what parameters have been provided 
    // in case 0, variables are initialized to default values; if 1, an array is provided, and, finally,
    // if the value is 2 a constant in provided in the file
    int behaviours_provided, delays_provided, weights_provided, training_zones_provided, 
        thresholds_provided, v_rests_provided, refract_times_provided, R_provided; // TODO: add more 

} simulation_configuration_t;


/// @brief Struct containing the information to initialize each neuron and synapse
typedef struct{
    
    // general network information
    size_t n_neurons, n_input_neurons, n_output_neurons, n_synapses, n_input_synapses, n_output_synapses, max_delay;

    // connectivity
    int *neuron_excitatory, *training_zones; // change to uint in the future
    int *delay_list;
    double *weight_list;
    int **synaptic_connections;
    
    // LIF neuron
    double *v_list, *v_thres_list, *v_rest_list, *R_list; // parameters for all neurons [n_neurons]
    int *r_time_list; // refractory times for all neurons [n_neurons] 

} network_construction_lists_t;



/* Struct for simualtion results */

/// [DEPRECATED]
/// @brief Struct to store the results of each sample
typedef struct{
    
    // elapsed time for different sections of the simulation
    double elapsed_time_neurons; // elapsed time computing neurons
    double elapsed_time_neurons_input; // elapsed time processing neurons input 
    double elapsed_time_neurons_output; // elapsed time processing neurons output
    double elapsed_time_synapses; // elapsed time processing synapses
    double elapsed_time_synapses_input; // elapsed time processing synapses input
    double elapsed_time_synapses_output; // elapsed time processing synapses output
    double elapsed_time_learning; // elapsed time processing learning rules
    double elapsed_time_sample, elapsed_time_load_sample;
    double elapsed_time_re_neurons, elapsed_time_re_synapses;

    // information about generated spikes
    unsigned char **generated_spikes; // generated spikes [n_neurons x n_time_steps]
    int *n_spikes_per_neuron; // number of spikes per each neuron [n_samples x n_neurons]

} simulation_results_per_sample_t;


/// [DEPRECATED]
/// @brief Struct to store the general results of the simulation
typedef struct{
    
    simulation_results_per_sample_t *results_per_sample; // [n_samples]
    double elapsed_time_epoch, elapsed_time, elapsed_time_batch;
    double elapsed_time_total_inference;
    double elapsed_time_total_learning;

    double elapsed_time_neurons; // elapsed time computing neurons
    double elapsed_time_neurons_input; // elapsed time processing neurons input 
    double elapsed_time_neurons_output; // elapsed time processing neurons output
    double elapsed_time_synapses; // elapsed time processing synapses
    double elapsed_time_synapses_input; // elapsed time processing synapses input
    double elapsed_time_synapses_output; // elapsed time processing synapses output
    double elapsed_time_learning; // elapsed time processing learning rules
    double elapsed_time_sample, elapsed_time_load_sample;
    double elapsed_time_re_neurons, elapsed_time_re_synapses;

} simulation_results_t;


/* Structs for datasets */

/// [DEPRECATED]
// struct to represent a spike train
typedef struct{

    int n_spikes; // number of spikes in the train
    int *stimes; // spike times
    
} spike_train_t;


/// [DEPRECATED]
// spike image (set of spike trains)
typedef struct{

    spike_train_t *st; // pixels

} sample_t;


/// [DEPRECATED]
/// @brief Struct to handle different data types
typedef struct{

    int n_samples; // number of samples in the dataset
    int type; // image, ...

    // images
    int image_size; // number of pixels []
    sample_t *samples; // samples in the dataset

    // general information
    int n_classes;
    int *labels; // labels of each sample
    
} input_data_t;


/* Network structs */

/// [DEPRECATED]
/// @brief LIF neuron model structure
typedef struct {

    // input synapses
    int *input_synapse_indexes; // indexes of input synapses in the synase array
    int n_input_synapse; // number of input synapses
    int *next_spike_index; // indexes of the next spike to compute for each input synapse
    int next_input_synapse; // used in initialization

    // output synapses
    int *output_synapse_indexes; // indexes of output synapses in the synapse array
    int n_output_synapse; // number of output synapses
    int next_output_synapse; // used in initialization

    // is input ot output neuron // not necessary? It depends on the position
    int is_input_neuron; // neuron is an input neuron (in the network)
    int is_output_neuron; // neuron is an output neuron (in the network)

    // TODO: actually used?
    int excitatory; // neuron behaviour

    // neuron variables
    double v; // membrane potential
    double r; // neuron resistance
    double v_rest; // neuron resting potential
    double v_tresh; // neuron threshold potential
    int r_time; // refractory time
    int r_time_rest; // resting time in refractory period

    // circular array array of last timestamps of generated spikes 
    //int *t_last_spikes; // DEPRECATED?
    //int n_last_spikes; // DEPRECATED? 
    //int next_last_spike; // DEPRECATED?


    // array to store spikes generated by the neuron // TODO: probably I will move this to a separated matrix
    int *spike_times_arr; // circular array to store spikes // TODO: this MUST be refactorized
    int last_spike; // indexes of next spike to fire and the last produced // TODO: I really don't understand very good this indexes in this moment
    int max_spikes; // array length

    //int highest_post_delay;

} lif_neuron_t;


/// [DEPRECATED]
// define synapse_t struct
typedef struct synapse_t synapse_t;


/// [DEPRECATED]
/// @brief Synapse structure
struct synapse_t {

    // synapse variables
    double w; // synapse weight
    double init_w;
    double dw; // weight change
    int delay; // latency

    int lr; // learning rule index
    void (*learning_rule)(synapse_t*, int, int); // pointer to learning rule function // this parameter should be an struct?
    int stdp_steps; // to compute N step STDP;
    int next_pre_spike, next_post_spike;

    //int t_last_pre_spike, t_last_post_spike; // times of last presynaptic neuron and postsynaptic neurons spikes // if the difference in performance is not critical, this should be removed and neurons directly used

    // probably I shoudl implement another way to handle different types of neurons

    // presynaptic neuron
    lif_neuron_t *pre_synaptic_lif_neuron; // reference to presynaptic neuron
    int pre_neuron_index;
    
    // postsynaptic neuron
    lif_neuron_t *post_synaptic_lif_neuron; // reference to postynaptic neuron
    int post_neuron_index;

};

/// [DEPRECATED]
typedef struct spiking_nn_t spiking_nn_t;

/// [DEPRECATED]
/// @brief SNN structure 
struct spiking_nn_t{

    // network general information
    int neuron_type; // neuron type: LIF (0)

    int n_neurons; // number neurons 
    int n_input; // number of input neurons
    int n_output; // number of output neurons

    int n_synapses; // number of synapses
    int n_input_synapses; // number of input synapses
    int n_output_synapses; // number of output synapses

    // array of neurons (an array for each neuron type)
    lif_neuron_t *lif_neurons; 
    //hh_neuron_t *hh_neurons; // TODO

    // function pointers dependent of neuron type
    void (*neuron_initializer)(spiking_nn_t *, int, network_construction_lists_t*, int, int, int); 
    void (*neuron_re_initializer)(spiking_nn_t *, int); // function pointers to initialize neurons
    void (*complete_step)(spiking_nn_t*, int, int, simulation_results_per_sample_t*); 
    void (*input_step)(spiking_nn_t*, int, int, simulation_results_per_sample_t*, simulation_configuration_t *); 
    void (*output_step)(spiking_nn_t*, int, int, simulation_results_per_sample_t*, simulation_configuration_t *); // functions pointers to simulate networks
    void (*load_sample)(spiking_nn_t*, sample_t*);

    // array of synapses
    synapse_t *synapses;

    // input neurons array ("virtual neurons" not included in the network, only used to fire input spikes)
    lif_neuron_t *input_lif_neurons; // only used to introduce data in the network

};

// struct to store the samples in a batch
typedef struct {

    char *spikes;

} tmp_batch_cpu_t;

/* New structs */



/// @brief SNN structure
typedef struct {

    // char is used to reduce memory usage
    size_t neuron_type;
    size_t n_neurons;
    size_t n_input_neurons;
    size_t n_output_neurons;
    size_t n_synapses;
    size_t n_input_synapses;
    size_t n_output_synapses;
    size_t max_spikes;
    size_t n_networks;
    size_t max_delay;
    size_t LT; // matrix L dimension

    // neccessary parameters for all neurons
    float *v; // [n_neurons]: membrane potential of the neuron
    float *v_thresh; // [n_neurons]: threshold of the neuron
    float *v_rest; // [n_neurons]: resting potential of the neuron
    int *r_period; // [n_neurons]: refractary period of the neuron
    int *r_period_remain; // [n_neurons]: remaining refractory period of the neuron
    int *res; // [n_neurons]: resistance of the neuron
    char *post_fired; // [n_neurons]: describes if neuron fired on time t
    float *post_trace; // [n_neurons]: postsynaptic trace
    float *arrI; // [n_neurons]: input current in the time step
    int *inR; // [n_neurons]: neuron in refractary period // [DEPRECATED]
    
    size_t *n_neuron_input_synapses; // [n_neurons]: number of input synapses for the neuron
    size_t *neuron_input_synapses_offset; // [n_neurons]: index of the first input synapse for each neuron
    size_t *n_neuron_output_synapses; // [n_neurons]: number of output synapses for the neuron
    size_t *neuron_output_synapses_offset; // [n_neurons]: index of the first output synapse for each neuron
    

    // synapses
    float *w; // [n_synapses]: weight of the synapse
    float *init_w; // [n_synapses]: initial weight of the synapse
    float *dw; // [n_synapses]: weight difference of the synapse
    float *acc_dw; // [n_synapses]: accumulated dw for all batch elements
    int *delay; // [n_synapses]: delay or latency of the synapse
    int *lr; // [n_synapses]: learning rule of the synapse
    size_t *pre_neuron_index; // [n_synapses]: index of the presynaptic neuron
    size_t *post_neuron_index; // [n_synapses]: index of the postsynaptic neuron
    char *pre_fired; // [n_synapses]: describes if the presynaptic neuron fired
    float *pre_trace; // [n_synapses]: presynaptic trace

    char *spk_matrix; // [(n_input_synapses + n_neurons) * t_len * batch_size]

    // FLOAT(3N + 2M) + INT(7N + 5M) + NT = 32(10N + 7M) + 32NT bit

    // N = 1.000; M = 100.000; T = 500; 32(10.000 + 700.000 + 500.000) = 32 * 1.210.000 = 38.720.000 = 0,0045 GB
    // N = 100.000; M = 100.000.000; T = 500; COST = 24.032.000.000 = 2,8 GB

  // it should be helpfull to add output synapses to compute STDP easier?
  // neurons are processed? Those variables could help

} GPU_SNN_t;


/// @brief Structure to store the dataset
// [TODO]: Chunks?
typedef struct {

    int type; // dataset type
    size_t n_classes; // number of classes in the dataset

    size_t n_samples; // number of samples in the dataset
    size_t n_features; // number of features of the samples
    size_t *n_spikes_per_feature; // [n_samples * n_features]: number of spikes per each feature 

    size_t *sample_offset; // [n_samples]: offset that indicates where each sample starts in "spikes" array   
    size_t *feature_offset; // [n_samples * n_features]: offset that indicates where each feature starts in "spikes" array

    size_t *spikes; // entire dataset (spike times)
    size_t n_spikes; // total number of spikes in the dataset

    size_t *freq; // spike trains described by frequencies
    size_t *first_spk; // first spike time

} GPU_dataset_t;


/// @brief Structure to store results during simulation
typedef struct {

    // generated spikes output
    int *n_spks; // [n_samples * n_neurons]
    char *gnt_spks; // [n_samples * n_neurons * timesteps] // TODO: remove in the future

    // time variables
    double t; // total execution time
    double t_in; // time processing input spikes
    double t_v; // time processing neurons dynamics
    double t_out; // time processing output spikes
    double t_learn; // time learning
    double t_reinit; // network reinitialization
    double t_load; // loading sample or batch in network

} GPU_results_t;



/// @brief Struct that stores data to guide the cuda simulation
typedef struct {

    // devices data
    int multi_gpu_allowed; // wether multilple devices should be used
    size_t nDevices; // number of available devices
    double *gpu_total_mem; // free memory in the GPU
    double *gpu_free_mem; // memory available in the GPU
    double *shared_memory_mem; // Bytes in shared memory
    // TOOD: max threads....

    // cuda simulation details (network size, dataset size...)
    double dataset_size; // dataset size
    double network_size; // network size
    double network_cpy_size; // size of each network copy
    double results_size; // results size

    double *neuron_size; // size related to each neuron
    double *batch_neuron_size; // size related to the entire neuron batch 
    double *synapse_size; // size related to each synapse
    double *batch_synapse_size; // size related to the entire synapse batch

    size_t n_networks; // DEPRECATED // n copies of the network in the GPU
    size_t n_samples; // n samples in the dataset
    size_t batch_size; // batch_size of the simulation
    size_t time_steps; // time steps of the simulation
    
    size_t batch_size_per_block;
    size_t *blocks_per_batch;

    
    // multigpu control variables
    size_t *dev_batch_size; // [nDevices] part of the batch simulated by each device
    size_t *dev_batch_offset; // [nDevices] the first sample in the batch to be simulated by device 
    size_t *n_networks_per_dev; // [nDevices]: number of copies on each device

    size_t gpuId; // used to index the correct information on each GPU
    
    
    // helpers for weight updating
    GPU_SNN_t **tmp_snn; // tmp snn structure
    float **dw; // dw [nDevices, nSynapses]     


    // number of threads and blocks per kernel
    size_t *n_thr_per_blk_neurons_x, *n_thr_per_blk_neurons_y, *n_thr_per_blk_neurons_z;
    size_t *n_thr_per_blk_synapses_x, *n_thr_per_blk_synapses_y, *n_thr_per_blk_synapses_z;
    size_t *n_thr_per_blk_in_neurons_x, *n_thr_per_blk_in_neurons_y, *n_thr_per_blk_in_neurons_z;
    size_t *n_thr_per_blk_all_neurons_x, *n_thr_per_blk_all_neurons_y, *n_thr_per_blk_all_neurons_z;
    size_t *n_thr_per_blk_uw_x, *n_thr_per_blk_uw_y, *n_thr_per_blk_uw_z;
    size_t *n_thr_per_blk_is_x, *n_thr_per_blk_is_y, *n_thr_per_blk_is_z;

    size_t *n_blk_neurons_x, *n_blk_neurons_y, *n_blk_neurons_z;
    size_t *n_blk_synapses_x, *n_blk_synapses_y, *n_blk_synapses_z;
    size_t *n_blk_in_neurons_x, *n_blk_in_neurons_y, *n_blk_in_neurons_z;
    size_t *n_blk_all_neurons_x, *n_blk_all_neurons_y, *n_blk_all_neurons_z;
    size_t *n_blk_uw_x, *n_blk_uw_y, *n_blk_uw_z;
    size_t *n_blk_is_x, *n_blk_is_y, *n_blk_is_z; 

    size_t *n_threads_per_blk_synapses_x, *n_threads_per_blk_synapses_y, *n_threads_per_blk_synapses_z;

} cuda_info_t;



/* General function to network initialization */

///
#ifdef __cplusplus
extern "C" {
#endif


GPU_SNN_t* initialize_network_cpu(simulation_configuration_t *conf, network_construction_lists_t *data);
void print_network(GPU_SNN_t *snn);
void print_networks(GPU_SNN_t *snn, simulation_configuration_t *conf);
void print_dataset(GPU_dataset_t *dataset);
void cpy_snn(GPU_SNN_t *snn, simulation_configuration_t *conf);
void reallocate_spk_matrix(GPU_SNN_t *snn, size_t N, size_t B, size_t T);
// Functions to compute the memory occupated by structures
double get_snn_size(GPU_SNN_t *snn);
double get_snn_cpy_size(GPU_SNN_t *snn);
double get_dataset_size(GPU_dataset_t *dataset);
double get_results_size(size_t N, size_t nS, size_t T);
double get_tmp_batch_size(size_t iN, size_t nS, size_t T);

void configure_cuda_simulation(cuda_info_t *cuda_info, GPU_SNN_t *snn, GPU_dataset_t *dataset, simulation_configuration_t *conf);
GPU_results_t* initialize_batch_results_cpu(simulation_configuration_t *conf, size_t N, size_t batch_size, size_t T);
void reinitialize_batch_results_cpu(GPU_results_t *results, simulation_configuration_t *conf, size_t N, size_t batch_size, size_t T);
void deallocate_results_struct(GPU_results_t *results, simulation_configuration_t *conf);
void acc_batch_execution_times(GPU_results_t *results, GPU_results_t *batch_results);

#ifdef __cplusplus
}
#endif




/// @brief Function to initialize the SNN structure
/// @param snn SNN structure to be initialized
/// @param conf Struct that contains the configuration data to initialize the network
/// @param data Data to initialize the network 
void initialize_network(spiking_nn_t *snn, simulation_configuration_t *conf, network_construction_lists_t *data);

/// @brief Function to initialize the function pointers to avoid conditions during the simulation
/// @param snn 
void initialize_network_function_pointers(spiking_nn_t *snn);


/* Functions related to neurons initialization */

/// @brief Function to initialize the neurons in the networks
/// @param snn SNN structure to initialize neurons in
/// @param lists array containing the data to initialize neurons
void initialize_neurons(spiking_nn_t *snn, simulation_configuration_t *conf, network_construction_lists_t *data);

// !!!! Neurons initilization functions are located in their respective files in neuron_models directory


/* Functions related to synapses initialization */

/// @brief Function to initialize all synapses in the network
/// @param snn SNN structure to initialize synapses in
/// @param n_synapses Number of synapses in the network
/// @param data Structure containing the data to initialize synapses
void initialize_synapses(spiking_nn_t *snn, int n_synapses, simulation_configuration_t *conf, network_construction_lists_t *data);

/// @brief Function to initialize a synapse
/// @param synapse Synapse structure to be initialized
/// @param data Structure containing the data to initialize the synapse with
/// @param snn SNN structure
/// @param synapse_id Neuron index in the synapses array
void initialize_synapse(synapse_t *synapse, network_construction_lists_t *data, spiking_nn_t *snn, int synapse_id);

/// @brief Function to reinitialize synapses
/// @param snn SNN structure to reinitialize synapases in
void re_initialize_synapses(spiking_nn_t *snn);

/// @brief Function to reinitialize a synapse
/// @param synapse Synapse to be reinitialized
void re_initialize_synapse(synapse_t *synapse);

/// @brief 
/// @param snn 
void update_weights(spiking_nn_t *snn);

/// @brief 
/// @param synapse 
void update_weight(synapse_t *synapse);


/* Functions to connect neurons and synapses */

/// @brief Connect neuron to input and output synapses
/// @param snn SNN structure
/// @param synapse_matrix Synapse matrix 
void connect_neurons_and_synapses(spiking_nn_t *snn, int **synaptic_connections);

/// @brief Add input synapse to a neuron
/// @param snn SNN structure
/// @param neuron_index Index of the neuron to add a synapse
/// @param synapse_index Index of the synapse to be added as input to neuron
void add_input_synapse_to_neuron(spiking_nn_t *snn, int neuron_index, int synapse_index);

/// @brief Add output synapse to a neuron
/// @param snn SNN structure
/// @param neuron_index Index of the neuron to add a synapse
/// @param synapse_index Index of the synapse to be added as output to neuron
void add_output_synapse_to_neuron(spiking_nn_t *snn, int neuron_index, int synapse_index);

/// ACTUALLY DEPRECATED
/// @brief Initialize weights of the network
/// @param snn Spiking neural network structure
void initialize_network_weights(spiking_nn_t *snn);



/* Function to copy networks */

/// @brief Function to copy a SNN structure
/// @param cp_snn Copied SNN struct
/// @param or_snn Original SNN struct
/// @param conf Configuration infor to help the copy process
void cp_network(spiking_nn_t *cp_snn, spiking_nn_t *or_snn, simulation_configuration_t *conf);

/// @brief Function to copy neurons
/// @param cp_snn Struct to copy neurons in
/// @param or_snn Struct to copy neurons from
void cp_neurons(spiking_nn_t *cp_snn, spiking_nn_t *or_snn);

/// @brief 
/// @param cp_snn 
/// @param or_snn 
void cp_input_neurons(spiking_nn_t *cp_snn, spiking_nn_t *or_snn);

/// @brief Function to copy synapses
/// @param cp_snn Struct to copy synapses in
/// @param or_snn Struct to copy synapses from
void cp_synapses(spiking_nn_t *cp_snn, spiking_nn_t *or_snn);


/* Other functions */

/// @brief This function reorders the list of synapses and local list of synapse indexes of neurons following the input criterion
/// @param snn Spiking neural network structure to reorder synapses
void reorder_synapse_list(spiking_nn_t *snn);



/* CPU2GPU mapping functions */
GPU_SNN_t* SNN_CPU2GPU_mapping(spiking_nn_t *snn, simulation_configuration_t *conf);
GPU_dataset_t* dataset_CPU2GPU_mapping(input_data_t *dataset, simulation_configuration_t *conf);



//
void free_gpu_snn_in_CPU(GPU_SNN_t *gpu_snn);
void free_gpu_dataset_in_CPU(GPU_dataset_t *gpu_dataset);
void free_gpu_results_in_CPU(GPU_results_t *gpu_results);


/* Functions for results structs */

/// @brief Function to initialize results struct
/// @param results Structure to store results
/// @param conf Structure containing information about the configuration of the simulation
void initialize_results_struct(simulation_results_t *results, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief Function to initialize the structure for the results of a sample
/// @param results_per_sample Structure to store the results of a sample
/// @param conf Structure containing information about the configuration of the simulation
void initialize_sample_results_struct(simulation_results_per_sample_t *results_per_sample, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief Function to reinitialize results structure
/// @param results 
/// @param conf 
void reinitialize_results_struct(simulation_results_t *results, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief Function to reinitialize a struct to store results of a sample
/// @param results_per_sample 
/// @param conf 
void reinitialize_sample_results_struct(simulation_results_per_sample_t *results_per_sample, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief TODO
/// @param results 
/// @param conf 
void free_results_struct_memory(simulation_results_t *results, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief TODO
/// @param results_per_sample 
/// @param conf 
void free_sample_results_struct_memory(simulation_results_per_sample_t *results_per_sample, simulation_configuration_t *conf, int n_samples, int n_neurons);


/* Functions to allocate and free memory */

// TODO

/// @brief Function to free the memory of the lists used to initialize the network
/// @param lists Structure of lists to free
/// @param snn Spiking neural network structure
void free_lists_memory(network_construction_lists_t *lists, spiking_nn_t *snn);
void free_snn_struct_memory(spiking_nn_t *snn);
void free_lif_neurons(spiking_nn_t *snn);
void free_synapses(spiking_nn_t *snn);



/* Functions to print the network information */

/// @brief
/// @param
void print_lif_neuron_information(lif_neuron_t *lif_neuron);

/// @brief
/// @param
void print_lif_neurons_information(spiking_nn_t *snn);

/// @brief
/// @param
void print_neurons_information(spiking_nn_t *snn);

/// @brief
/// @param
void print_input_synapse_information(synapse_t *synapse);

/// @brief
/// @param
void print_synapse_information(synapse_t *synapse);

/// @brief
/// @param
void print_output_synapse_information(synapse_t *synapse);

/// @brief
/// @param
void print_synapses_information(spiking_nn_t *snn);

/// @brief
/// @param
void print_network_information(spiking_nn_t *snn);

#endif
