#ifndef SNN_LIBRARY_H
#define SNN_LIBRARY_H

// max spikes to store per synapse
#ifndef MAX_SPIKES
#define MAX_SPIKES 200 
#endif
// I have to change the way I manage the input
#ifndef INPUT_MAX_SPIKES
#define INPUT_MAX_SPIKES 500 
#endif


// TODO: Max spikes should be an input parameter?


/* Simulation configuration struct containing all the data for the simulation */

/// @brief Struct to load all the configuration data
typedef struct{

    // [general] information
    int simulation_type; // clock (0) / event-driven (1)
    int neuron_type; // neuron type (LIF...)
    int simulation_obj; // simulation obj. (ML or biological simulations) // DEPRECATED???
    int n_process; // number of CPU processes
    int cuda; // simulation done in cuda
    int learn; // inference (0) / training (1)
    int encode; // input encoded (0) / encode input (1) // TODO

    // [simulation] data
    int time_steps; // time steps of the simulations
    int max_spikes; // length for arrays in the middle of the network
    int max_input_spikes; // length for input and output neurons arrays

    // [dataset] data
    char *train_set; // path to the file that contains the train set
    char *train_labels; // path to the file that contains the labels of the train set
    int n_train; // number of samples in the training set

    int test_provided; // indicates if a test set exists (1) or not (0)
    char *test_set; // path to the file that contains the test set
    char *test_labels; // path to the file that contains the labels of the test set
    int n_test; // number of samples in the test set
    
    char *dataset_name; // name of the simulated dataset
    int n_classes; // number of classes in the dataset
    int epochs; // number of epochs to simulate
    int input_size;

    // [output] data
    char *generated_spikes_file; // file path to store the spike generated
    char *n_spikes_per_neuron_file; // file path to store the number of spikes generated by each sample
    char *execution_times_file; // file path to store the execution times
    int store_final_network; // store the final network (1) or not (0)
    char *final_network_file; // file path to store the final network

    // [network] section
    char *network_file; // file path to load the network from 
    char *network_neurons_file; // file path to load network neurons from 
    char *network_synapses_file; // file path to load network synapses from

    // control variables to indicate what parameters have been provided // Probably deprecated???
    int behaviours_provided, delays_provided, weights_provided, training_zones_provided, 
        thresholds_provided, v_rests_provided, refract_times_provided, R_provided; // TODO: add more 

} simulation_configuration_t;


/// @brief Struct containing the information to initialize each neuron and synapse
typedef struct{
    
    // connectivity
    int **synaptic_connections, *neuron_excitatory, *training_zones; // change to uint in the future
    int *delay_list;
    double *weight_list;

    // LIF neuron
    double *v_list, *v_thres_list, *v_rest_list, *R_list; // parameters for all neurons [n_neurons]
    int *r_time_list; // refractory times for all neurons [n_neurons] 

} network_construction_lists_t;



/* Struct for simualtion results */

/// @brief Struct to store the results of each sample
typedef struct{
    
    // elapsed time for different sections of the simulation
    double elapsed_time_neurons; // elapsed time computing neurons
    double elapsed_time_neurons_input; // elapsed time processing neurons input 
    double elapsed_time_neurons_output; // elapsed time processing neurons output
    double elapsed_time_synapses; // elapsed time processing synapses
    double elapsed_time_synapses_input; // elapsed time processing synapses input
    double elapsed_time_synapses_output; // elapsed time processing synapses output
    double elapsed_time_learning; // elapsed time processing learning rules
    double elapsed_time_sample, elapsed_time_load_sample;
    double elapsed_time_re_neurons, elapsed_time_re_synapses;

    // information about generated spikes
    unsigned char **generated_spikes; // generated spikes [n_neurons x n_time_steps]
    int *n_spikes_per_neuron; // number of spikes per each neuron [n_samples x n_neurons]

} simulation_results_per_sample_t;


/// @brief Struct to store the general results of the simulation
typedef struct{
    
    simulation_results_per_sample_t *results_per_sample; // [n_samples]
    double elapsed_time_epoch, elapsed_time;

} simulation_results_t;


/* Structs for datasets */

// The implementation must be generalized to these structs

// struct to represent a spike train
typedef struct{

    int n_spikes; // number of spikes in the train
    int *stimes; // spike times
    
} spike_train_t;


// spike image (set of spike trains)
typedef struct{

    spike_train_t *st; // pixels

} sample_t;

/// @brief Struct to handle different data types
typedef struct{

    int n_samples; // number of samples in the dataset
    int type; // image, ...

    // images
    int image_size; // number of pixels []
    sample_t *samples; // samples in the dataset

    // general information
    int n_classes;
    int *labels; // labels of each sample
    
} input_data_t;



/* Network structs */

/// @brief LIF neuron model structure
typedef struct {

    // input synapses
    int *input_synapse_indexes; // indexes of input synapses in the synase array
    int n_input_synapse; // number of input synapses
    int *next_spike_index; // indexes of the next spike to compute for each input synapse
    int next_input_synapse; // used in initialization

    // output synapses
    int *output_synapse_indexes; // indexes of output synapses in the synapse array
    int n_output_synapse; // number of output synapses
    int next_output_synapse; // used in initialization

    // is input ot output neuron // not necessary? It depends on the position
    int is_input_neuron; // neuron is an input neuron (in the network)
    int is_output_neuron; // neuron is an output neuron (in the network)

    // TODO: actually used?
    int excitatory; // neuron behaviour

    // neuron variables
    double v; // membrane potential
    double r; // neuron resistance
    double v_rest; // neuron resting potential
    double v_tresh; // neuron threshold potential
    int r_time; // refractory time
    int r_time_rest; // resting time in refractory period

    // time step in which the last spike was generated
    int t_last_spike; 


    // array to store spikes generated by the neuron // TODO: probably I will move this to a separated matrix
    int *spike_times_arr; // circular array to store spikes // TODO: this MUST be refactorized
    int last_spike; // indexes of next spike to fire and the last produced // TODO: I really don't understand very good this indexes in this moment
    int max_spikes; // array length

    //int highest_post_delay;

} lif_neuron_t;

// define synapse_t struct
typedef struct synapse_t synapse_t;


/// @brief Synapse structure
struct synapse_t {

    // synapse variables
    double w; // synapse weight
    double dw; // weight change
    int delay; // latency

    int lr; // learning rule index
    void (*learning_rule)(synapse_t*, int); // pointer to learning rule function // this parameter should be an struct?


    //int t_last_pre_spike, t_last_post_spike; // times of last presynaptic neuron and postsynaptic neurons spikes // if the difference in performance is not critical, this should be removed and neurons directly used

    // probably I shoudl implement another way to handle different types of neurons

    // presynaptic neuron
    lif_neuron_t *pre_synaptic_lif_neuron; // reference to presynaptic neuron
    int pre_neuron_index;
    
    // postsynaptic neuron
    lif_neuron_t *post_synaptic_lif_neuron; // reference to postynaptic neuron
    int post_neuron_index;

};

typedef struct spiking_nn_t spiking_nn_t;

/// @brief SNN structure 
struct spiking_nn_t{

    // network general information
    int n_neurons; // number neurons 
    int n_input; // number of input neurons
    int n_output; // number of output neurons
    int neuron_type; // neuron type: LIF (0)

    int n_synapses; // number of synapses
    int n_input_synapses; // number of input synapses
    int n_output_synapses; // number of output synapses

    // array of neurons (an array for each neuron type)
    lif_neuron_t *lif_neurons; 
    //hh_neuron_t *hh_neurons; // TODO

    // function pointers dependent of neuron type
    void (*neuron_initializer)(spiking_nn_t *, int, network_construction_lists_t*, int, int); 
    void (*neuron_re_initializer)(spiking_nn_t *, int); // function pointers to initialize neurons
    void (*complete_step)(spiking_nn_t*, int, int, simulation_results_per_sample_t*); 
    void (*input_step)(spiking_nn_t*, int, int, simulation_results_per_sample_t*); 
    void (*output_step)(spiking_nn_t*, int, int, simulation_results_per_sample_t*); // functions pointers to simulate networks
    void (*load_sample)(spiking_nn_t*, sample_t*);

    // array of synapses
    synapse_t *synapses;
    double *Dw;

    // input neurons array ("virtual neurons" not included in the network, only used to fire input spikes)
    lif_neuron_t *input_lif_neurons; // only used to introduce data in the network

};


/* General function to network initialization */

/// @brief Function to initialize the SNN structure
/// @param snn SNN structure to be initialized
/// @param conf Struct that contains the configuration data to initialize the network
/// @param data Data to initialize the network 
void initialize_network(spiking_nn_t *snn, simulation_configuration_t *conf, network_construction_lists_t *data);

/// @brief Function to initialize the function pointers to avoid conditions during the simulation
/// @param snn 
void initialize_network_function_pointers(spiking_nn_t *snn);


/* Functions related to neurons initialization */

/// @brief Function to initialize the neurons in the networks
/// @param snn SNN structure to initialize neurons in
/// @param lists array containing the data to initialize neurons
void initialize_neurons(spiking_nn_t *snn, network_construction_lists_t *data);

// !!!! Neurons initilization functions are located in their respective files in neuron_models directory


/* Functions related to synapses initialization */

/// @brief Function to initialize all synapses in the network
/// @param snn SNN structure to initialize synapses in
/// @param n_synapses Number of synapses in the network
/// @param data Structure containing the data to initialize synapses
void initialize_synapses(spiking_nn_t *snn, int n_synapses, network_construction_lists_t *data);

/// @brief Function to initialize a synapse
/// @param synapse Synapse structure to be initialized
/// @param data Structure containing the data to initialize the synapse with
/// @param snn SNN structure
/// @param synapse_id Neuron index in the synapses array
void initialize_synapse(synapse_t *synapse, network_construction_lists_t *data, spiking_nn_t *snn, int synapse_id);

/// @brief Function to reinitialize synapses
/// @param snn SNN structure to reinitialize synapases in
void re_initialize_synapses(spiking_nn_t *snn);

/// @brief Function to reinitialize a synapse
/// @param synapse Synapse to be reinitialized
void re_initialize_synapse(synapse_t *synapse);

/// @brief 
/// @param snn 
void update_weights(spiking_nn_t *snn);

/// @brief 
/// @param synapse 
void update_weight(synapse_t *synapse);


/* Functions to connect neurons and synapses */

/// @brief Connect neuron to input and output synapses
/// @param snn SNN structure
/// @param synapse_matrix Synapse matrix 
void connect_neurons_and_synapses(spiking_nn_t *snn, int **synaptic_connections);

/// @brief Add input synapse to a neuron
/// @param snn SNN structure
/// @param neuron_index Index of the neuron to add a synapse
/// @param synapse_index Index of the synapse to be added as input to neuron
void add_input_synapse_to_neuron(spiking_nn_t *snn, int neuron_index, int synapse_index);

/// @brief Add output synapse to a neuron
/// @param snn SNN structure
/// @param neuron_index Index of the neuron to add a synapse
/// @param synapse_index Index of the synapse to be added as output to neuron
void add_output_synapse_to_neuron(spiking_nn_t *snn, int neuron_index, int synapse_index);

/// ACTUALLY DEPRECATED
/// @brief Initialize weights of the network
/// @param snn Spiking neural network structure
void initialize_network_weights(spiking_nn_t *snn);



/* Function to copy networks */

/// @brief Function to copy a SNN structure
/// @param cp_snn Copied SNN struct
/// @param or_snn Original SNN struct
/// @param conf Configuration infor to help the copy process
void cp_network(spiking_nn_t *cp_snn, spiking_nn_t *or_snn, simulation_configuration_t *conf);

/// @brief Function to copy neurons
/// @param cp_snn Struct to copy neurons in
/// @param or_snn Struct to copy neurons from
void cp_neurons(spiking_nn_t *cp_snn, spiking_nn_t *or_snn);

/// @brief Function to copy synapses
/// @param cp_snn Struct to copy synapses in
/// @param or_snn Struct to copy synapses from
void cp_synapses(spiking_nn_t *cp_snn, spiking_nn_t *or_snn);


/* Other functions */

/// @brief This function reorders the list of synapses and local list of synapse indexes of neurons following the input criterion
/// @param snn Spiking neural network structure to reorder synapses
void reorder_synapse_list(spiking_nn_t *snn);




/* Functions for results structs */

/// @brief Function to initialize results struct
/// @param results Structure to store results
/// @param conf Structure containing information about the configuration of the simulation
void initialize_results_struct(simulation_results_t *results, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief Function to initialize the structure for the results of a sample
/// @param results_per_sample Structure to store the results of a sample
/// @param conf Structure containing information about the configuration of the simulation
void initialize_sample_results_struct(simulation_results_per_sample_t *results_per_sample, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief Function to reinitialize results structure
/// @param results 
/// @param conf 
void reinitialize_results_struct(simulation_results_t *results, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief Function to reinitialize a struct to store results of a sample
/// @param results_per_sample 
/// @param conf 
void reinitialize_sample_results_struct(simulation_results_per_sample_t *results_per_sample, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief TODO
/// @param results 
/// @param conf 
void free_results_struct_memory(simulation_results_t *results, simulation_configuration_t *conf, int n_samples, int n_neurons);

/// @brief TODO
/// @param results_per_sample 
/// @param conf 
void free_sample_results_struct_memory(simulation_results_per_sample_t *results_per_sample, simulation_configuration_t *conf, int n_samples, int n_neurons);


/* Functions to allocate and free memory */

// TODO

/// @brief Function to free the memory of the lists used to initialize the network
/// @param lists Structure of lists to free
/// @param snn Spiking neural network structure
void free_lists_memory(network_construction_lists_t *lists, spiking_nn_t *snn);
void free_snn_struct_memory(spiking_nn_t *snn);
void free_lif_neurons(spiking_nn_t *snn);
void free_synapses(spiking_nn_t *snn);



/* Functions to print the network information */

/// @brief
/// @param
void print_lif_neuron_information(lif_neuron_t *lif_neuron);

/// @brief
/// @param
void print_lif_neurons_information(spiking_nn_t *snn);

/// @brief
/// @param
void print_neurons_information(spiking_nn_t *snn);

/// @brief
/// @param
void print_input_synapse_information(synapse_t *synapse);

/// @brief
/// @param
void print_synapse_information(synapse_t *synapse);

/// @brief
/// @param
void print_output_synapse_information(synapse_t *synapse);

/// @brief
/// @param
void print_synapses_information(spiking_nn_t *snn);

/// @brief
/// @param
void print_network_information(spiking_nn_t *snn);

#endif
